process dns {
    run python3 -m exabgp healthcheck --config /etc/exabgp/health_check_dns;
    encoder text;
}
neighbor 100.64.33.10 {
    local-as 65001;
    local-address 100.64.33.20;
    peer-as 65000;
    hold-time 30;
    family {
        ipv4 unicast;
        ipv6 unicast;
    }
    api {
        processes [ dns ];
    }
}

