#process dns {
#    run python3 -m exabgp healthcheck --config /etc/exabgp/health_check_dns;
#    encoder text;
#}
neighbor 192.168.221.1 {
    local-as 64741;
    local-address 172.17.0.2;
    peer-as 64740;
    hold-time 30;
    family {
        ipv4 unicast;
    }
#    api {
#        processes [ dns ];
#    }
}

